### ISSUE TITLE
Search courses

### ISSUE THREAD

**Issue by qunabu** [EscolaLMS/Courses#30]
Everything should be within `GET /courses` endpoint 

**search critera**
- [x] by title LIKE 
- [x] by author_id
- [x] by tags (remove search by tags endpoint)
- [x] by categories (more search by cats endpoint) 

**order** 
- [x] ASC/DESC
- [x] by title
- [x] by created_by
- [x] base_price

**Task**
- [x] add logic to above 
- [x] add tests 
- [x] add swagger annotations 
- [x] remove tags/cats endpoints 
- [x] Results should be **paginated** (by default Laravel pagination) 

Refer to other project to see the implementation details 

<img width="1600" alt="Screenshot 2021-05-07 at 12 15 32" src="https://user-images.githubusercontent.com/214608/117435270-f55f8880-af2d-11eb-8b31-69773975ce17.png">
<img width="1603" alt="Screenshot 2021-05-07 at 12 12 49" src="https://user-images.githubusercontent.com/214608/117435278-f7c1e280-af2d-11eb-92f6-ae44cd8a1e0f.png">

**Comment by qunabu** [comment]
Seems related by `test_search_course_by_tag` stopped work int the lines 

```php
        foreach ($this->response->getData()->data->data as $data) {
            $this->assertFalse(empty($data->tags));

            foreach ($data->tags as $tag) {
                $this->assertTrue($tag->title === 'Fruit');
            }
        }
```
